### ISSUE TITLE
Unused keys from the configs.

### ISSUE THREAD

**Issue by dchaplinsky** [bminixhofer/ukrainian-wechsel-models#1]
Hello Benjamin! 

Thanks again for sharing the source code!

I have an issue when I'm trying to reproduce it.
I successfully ran prepare_model.py/prepare_data.py and got the model with embeddings aligned.
Now when I run `python run_mlm.py configs/roberta_ukrainian.json` it dies with the following error message:
```
ValueError: Some keys are not used by the HfArgumentParser: ['dtype', 'freeze_nonembedding_weights_steps']
```

And it seems that google has no idea, what `freeze_nonembedding_weights_steps` means. Like **zero results**.

Can I simply ignore those or remove them?

**Comment by bminixhofer** [comment]
Hi, these are leftovers from a slightly modified training script I used for some ablations in the paper (as the name suggests, the experiments where non-embedding weights are frozen at the start), feel free to remove them, sorry about the confusion. 

Let me know if you run into any other issues, and good luck with the model training!

**Comment by bminixhofer** [comment]
I'll keep this open until I get around to removing them from the configs.

**Comment by dchaplinsky** [comment]
Thanks. Another quick question. What dataset did you use for the validation, here: https://github.com/bminixhofer/ukrainian-wechsel-models/blob/main/prepare_data.py#L13

**Comment by bminixhofer** [comment]
I was looking through the code when I open sourced it, and this caught my eye as well. Sorry to say that I can not for the life of me remember. I don't think I used it in the end, you can just skip the deduplication.

**Comment by dchaplinsky** [comment]
Hello Benjamin!

I'm slowly moving forward; here are my objectives, plan, and issues I met.
### Objectives

- Familiarize me with the process of training and finetuning of LLMs
- Find the combination of the input params (texts, vectors, dictionaries) that gives the best possible result
- Apply it (alongside the other optimization techniques) to other LLMs doesn't exist for the Ukrainian yet

### Plan

- Give the code a minimal facelift to streamline the experiments and finetuning.
- Enable proper validation
- Reproduce your results from this repo
- Try different approaches to the corpora: a bigger one (like 3-4x the size of the Oscar 2019) and a smaller one ([150m](https://huggingface.co/datasets/lang-uk/uk150m) of tokens cherrypicked from corpora of 8b tokens using LSH with a very low threshold)
- Try a bigger en-uk dictionary
- Try better fasttext embeddings for Ukrainian, as we have some (https://aclanthology.org/2023.unlp-1.3/)
- Find the winning combo and apply it to, e.g, Mosaic LLM.

### Things were done so far
I've created a [fork of your repo](https://github.com/lang-uk/ukrainian-wechsel-models), did some housecleaning/housekeeping, re-enabled the validation, and made new configs for my experiments.
My test runs are [available here](https://wandb.ai/lang-uk/gpt-2-small-experiments). See the last two runs that basically reproduce your runs.

I've created a joint corpus (3-4x bigger) for further training.
I re-scraped the en-uk dictionary using your code from the wechsel, which gave me 2x more translations.
I'm working on an even bigger dictionary (more than 60k of articles, which puts it on par with the en-de dictionary).
I already have some fasttext vectors trained for Ukrainian language ([eg.1](https://huggingface.co/lang-uk/fasttext_uk_large), [eg.2](https://huggingface.co/lang-uk/fasttext_uk)).

### Issues and questions

- While I've tried to adhere to your approach, I cannot precisely reproduce the results you've got. I can see the 1.5x speedup on Wechsel over scratch, but the loss on the training dataset, in my cases, is visibly higher than the one you've reported on wandb.
- How do I resume the training properly? I've seen you did it successfully on GPT2-large for the Ukrainian language, and it preserved the steps and didn't mess up the LR schedule. When I tried to restart the training from a checkpoint, it messed up the LR schedule (and gave me an unpleasant loss spike too :)).
- I'm using "fp16": true to train my models, does it sounds ok? It seems that you were using an altered version of the transformers library, thus "dtype": "bfloat16".

**Comment by bminixhofer** [comment]
Thanks for the update!!

>  While I've tried to adhere to your approach, I cannot precisely reproduce the results you've got. I can see the 1.5x speedup on Wechsel over scratch, but the loss on the training dataset, in my cases, is visibly higher than the one you've reported on wandb.

I took a quick look at your runs. I believe the difference is due to a different effective batch size. I trained on a TPUv3-8, which has 8 cores, so the effective batch size was `per_device_train_batch_size x gradient_accumulation_steps x num_tpu_cores = 8 x 4 x 8 = 256`. 

> How do I resume the training properly? I've seen you did it successfully on GPT2-large for the Ukrainian language, and it preserved the steps and didn't mess up the LR schedule. When I tried to restart the training from a checkpoint, it messed up the LR schedule (and gave me an unpleasant loss spike too :)).

How did you resume training? The `resume_from_checkpoint` argument should do the trick.

> I'm using "fp16": true to train my models, does it sounds ok? It seems that you were using an altered version of the transformers library, thus "dtype": "bfloat16".

This may have been renamed to "bf16" in the transformers library? You should use bf16 instead of fp16 if your accelerator supports it. RTX GPUs and up support it if I remember correctly.

Also, since I noticed that the current runs are running on a quite small hardware setup, if you're looking for better hardware, I can recommend TPUs via the TPU Research Cloud (https://sites.research.google/trc/about/), I'm pretty sure they would happily sponsor your runs, and the code should work with them out of the box.

**Comment by dchaplinsky** [comment]
Thanks for your response!

> I took a quick look at your runs. I believe the difference is due to a different effective batch size. I trained on a TPUv3-8, which has 8 cores, so the effective batch size was per_device_train_batch_size x gradient_accumulation_steps x num_tpu_cores = 8 x 4 x 8 = 256.
In my case it is 8 x 4 x 2 = 64. Thanks for the hint, I'll try to compensate that with gradient accumulation. 

> This may have been renamed to "bf16" in the transformers library? You should use bf16 instead of fp16 if your accelerator supports it. RTX GPUs and up support it if I remember correctly.
Thanks, will try it.

> Also, since I noticed that the current runs are running on a quite small hardware setup
That is the way in some sense :) My 2x2 3090 setup allow me to run smaller experiments with limited compute budget. Once I'll have enough data prepared and the clear understanding what and how to train with this data — I'll apply for the TPU. One potential problem is that I don't have a proper affiliation (yet), so I'm not a scholar in a traditional way :)

Speaking of experiments. I ran few more experiments on top of baseline, maybe you'll find it useful:

- I've rescraped the dictionary from wiktionary, that gave me 2x more words but no improvement on the loss. The corresponding experiment has [mediumdict](https://wandb.ai/lang-uk/gpt-2-small-experiments/runs/mf0tx65b?workspace=user-chaplinsky-dmitry) infix in its name.
- I've converted another dictionary I found online, which is 4+x bigger than one you've used. That one give me a nice small improvement in loss/validation accuracy. It's called [largedict](https://wandb.ai/lang-uk/gpt-2-small-experiments/runs/ikyam16q?workspace=user-chaplinsky-dmitry).
- I've tried to couple largedict with a bigger fasttext embeddings we've trained for the wordnet project, and during `prepare_model` step it pulled to match all the tokens: `Matching token found for 50257 of 50257 tokens,` but again gave negative impact [on the loss](https://wandb.ai/lang-uk/gpt-2-small-experiments/runs/d8bn7akf?workspace=user-chaplinsky-dmitry).

**Comment by dchaplinsky** [comment]
Hello. Once again, here are a few updates:

- I've tried bf16 in different combinations with the grad accum settings, and every single time I ran it, it was a failure [1](https://wandb.ai/lang-uk/gpt-2-small-experiments/runs/7fle7g9t), [2](https://wandb.ai/lang-uk/gpt-2-small-experiments/runs/pe7icype?workspace=user-chaplinsky-dmitry) :)
- Ramping up GA 4x obviously gave a better loss curve, as, in fact, it reports the loss 4 times less often. But at least I've got an understanding of why your curves looked better than mine.
- I've made a few rounds trying to integrate SophiaG optimizers, and it looks like I finally made it work. Running it on vanilla params from the [repo](https://github.com/Liuhong99/Sophia), train run is available [here](https://wandb.ai/lang-uk/gpt-2-small-experiments/runs/ak7woddi?workspace=user-chaplinsky-dmitry).
- I've also added Lion Optimizer to the repo. Maybe I will give it a try.
As always, the progress can be [tracked here in my todo](https://github.com/lang-uk/ukrainian-wechsel-models/blob/main/better.todo).

I think by the end of this week, I'll be ready to train something bigger and newer than GPT2.

Could you please advise me on TPUs? Is that just a freeform application letter, or are there some obstacles/details I should know?

**Comment by dchaplinsky** [comment]
Hi @bminixhofer.

There are few updates on my ablation study, which I'd like to share with you.
I've tried different combinations, and here are the main finds on speed improvements.

Train loss, higher->lower
scratch on ukrainian oscar
wechsel on ukrainian oscar
wechsel with the better dict on ukrainian oscar
+ sophia optimizer
wechsel with the better dict on [malyuk corpus](https://huggingface.co/datasets/lang-uk/malyuk) + sophia optimizer

<img width="1567" alt="Screenshot 2023-06-15 at 02 05 22" src="https://github.com/bminixhofer/ukrainian-wechsel-models/assets/131186/83257187-872b-4597-8e80-b289f9a9882a">

Here is the zoomed version of the same graph in the beginning of the training:
<img width="1567" alt="Screenshot 2023-06-15 at 02 07 24" src="https://github.com/bminixhofer/ukrainian-wechsel-models/assets/131186/e55c3be8-9c95-4585-89d3-2b7f1a351d24">

I didn't include all the experiments I ran, only those that gave me a performance boost.
In short, on gpt2-small sophia optimizer gave the better boost at the beginning of the training, but tripling (or even quadrupling) the data gave the biggest impact on the long run.

The impact is even more visible on the validation accuracy graphs (unfortunately I only enabled it on the later runs).
<img width="1567" alt="Screenshot 2023-06-15 at 02 09 51" src="https://github.com/bminixhofer/ukrainian-wechsel-models/assets/131186/1c5a54ee-f3be-4fe6-a707-50269127129b">


Code is available in my fork of your repo, all the runs are [here](https://wandb.ai/lang-uk/gpt-2-small-experiments?workspace=user-chaplinsky-dmitry)

As per your advice, I applied for the TPU as I think I got some understanding of the optimal training regimes and now can apply it to the larger models on faster hardware.

The only thing I didn't fully cracked yet is MPT-7b, it's too big to fit my 24GB GPUs.

**Comment by bminixhofer** [comment]
Hi, thanks for the update! Sorry, I missed your previous message.

And congrats on the results, looks really good! How is the speed of sophia compared to adam, is it much slower? I've never used sophia before.

> As per your advice, I applied for the TPU as I think I got some understanding of the optimal training regimes and now can apply it to the larger models on faster hardware.

Let me know if you run into any problems. TPUs are not entirely straightforward to set up. I usually follow this guide: https://cloud.google.com/tpu/docs/tutorials/resnet-pytorch#xrt-legacy_1

You might want to initially stick to XRT, I am not sure if PJRT works with the HuggingFace trainer (although if you do get it to work, it's reportedly ~30% faster).

If you don't get access to TRC (although I'm pretty sure you will), let me know, I may still have some TPUs you can use.

**Comment by dchaplinsky** [comment]
> And congrats on the results, looks really good! How is the speed of sophia compared to adam, is it much slower? I've never used sophia before.

Speed was the same for me. Like, exactly the same, as well as memory consumption.

Thanks for your advice on TPUs!

**Comment by dchaplinsky** [comment]
Hmmm. You know what I found? That nicest bump and the best score is not because I've been training on 4x more data. Due to [mistake](https://github.com/lang-uk/ukrainian-wechsel-models/blob/main/configs/experimental/gpt2/gpt2-small.malyuk.filter.wechsel.largedict.sophia.json#L6
) in the training config it was the same data actually, oscar.

However the difference is related to the tokenizer, that was trained on the bigger corpus which later was used for the weights transfer using wechsel.

Which is a nice bug to have, because:
1. It shows the importance of the good tokenizer for wechsel
2. I can have even more improvements if I train on bigger corpus

**Comment by bminixhofer** [comment]
Interesting. Be really careful about comparing NLL loss / perplexity between models using different tokenizers though, they are generally not comparable (only if both tokenizers use the exact same amount of characters per token on average), ideal would be to use bits per character instead.

**Comment by dchaplinsky** [comment]
Hi Benjamin! Despite all my attempts to receive an access to TRC got me nowhere. I did two applications and wrote them on their support email with a detailed explanation about my project. 

Meanwhile I finished the ablation study training gpt2-small and roberta-base in a different regimes on a different datasets up to 50k steps on the hardware I own. Also me and @proger did the first BPC calculations and it looks like change of the tokenizer didn't affect the real performance.

If you can share your TRC leftovers I'd be super grateful. At the moment one of my servers hosted at the premises of Ukrainian Catholic University is out of business, since that university building has problems with electricity supply after the rocket strike last month.

Also, I'd like to ask your advice on training bigger models, where model weights + optimizer gradients doesn't fit into the VRAM even when I'm setting BS=1.

**Comment by dchaplinsky** [comment]
Oh!
> Thanks for your interest in the TRC program! We'd love to get you up and running with Cloud TPUs.

**Comment by bminixhofer** [comment]
Congrats!

> Also me and @proger did the first BPC calculations and it looks like change of the tokenizer didn't affect the real performance.

Do I understand correctly that this is a positive result (i.e. no performance degradation through the tokenizer swap)? If so, that's great!

> Also, I'd like to ask your advice on training bigger models, where model weights + optimizer gradients doesn't fit into the VRAM even when I'm setting BS=1.

Unfortunately I can't help too much there, so far I've (almost) only done training where the entire model fit into the memory of the accelerator. But on TPuv3-8's `roberta-large` and `gpt2-large` fit into memory so that's at least something. You can use `bf16` half-precision on TPUs to ~half the memory usage.

Beyond that, I'd recommend looking into LoRA / PEFT techniques. Might also be interesting to start from a much larger model like the recent LLama ones. For example something like this: https://arxiv.org/abs/2303.16199 (afaik they don't change the tokenizer though). I'm currently not doing fine-tuning / language transfer though so I'm not fully up to date there (since obviously it's very hard to keep up).

**Comment by dchaplinsky** [comment]
Thanks!
Yeah, BPC testing was positive. Still there might be a room for an error, but at least math looks good and BPC correlates with the loss curve and time spent on training. I'm yet to apply it to all the checkpoints I have.

I'm already using FP16 on nodes of 24GB of RAM. TPU3 has 32 AFAIK? Anyway, will look into it later, currently the plan is to transfer the training of the winning regimes to the TPUs and train models big and small.

Thanks for your help and advice!

**Comment by dchaplinsky** [comment]
Hi @bminixhofer!
One more clarification before I start using TPUs. You've been using one with the VM (which costs some money), right? Which VM is right for the LLM tasks (given the fact, I have 112gb of data to preprocess/train tokenizer on)?

**Comment by bminixhofer** [comment]
Yes, I've been using TPU VMs. They are part of the TRC program so they are free as well! You will pay for egress & ingress (which costs almost nothing) and, if you need to [mount a disk to your VM](https://cloud.google.com/tpu/docs/setup-persistent-disk) you'll need to pay for the disk as well. 

The disks are unfortunately not cheap, but depending on how much data you have you can use /dev/shm to repurpose some RAM as disk space to avoid using an extra disk. By default /dev/shm is 196GB iirc. Hope that helps!

**Comment by dchaplinsky** [comment]
Thanks, got it! 196GB is not enough, still it's manageable. I wish I didn't spend those 300$ credits long time ago on that account.

On a related note. Here is my scoreboard on NER using spacy/flair with different LLMs and LMs.
<img width="871" alt="Screenshot 2023-07-28 at 00 31 59" src="https://github.com/bminixhofer/ukrainian-wechsel-models/assets/131186/cd7432c7-d2af-4340-bb3e-007a867e417c">

As you can see, your models trained on Oscar has the best performance in their categories (number of parameters/size).

Will try to beat that with some extra computational power of TPUs.

**Comment by dchaplinsky** [comment]
Hi @bminixhofer.

I finally got my TPU instance (it took a while to wait for a free one) and managed to prepare data/model.

But it seems that training is running on CPU (very slow). I've tried to use xla_spawn.py and installed torch_xla, which again got me nothing.

I've tried to run run_clm.py example from google tpu's doc and it seemed to work.

Also, how do you monitor the TPU utilization/memory usage? Anything similar to nvtop?

**Comment by bminixhofer** [comment]
Hi, if you don't mind, let's continue this in an email thread (It's not 100% related to "unused keys from the configs" anymore anyway ;) ). Can you send me an email to kick it off?
